const List<String> departmentList = [
  'Educational Management and Planning (EDM)',
  ' Educational Foundations (EDF)',
  'Educational Psychology, Guidance and Counseling (EDP)',
  'Curriculum Studies and Educational Technology (EDC)',
  ' Human Kinetics and Health Education (KHE)',
  'Adult and Non-Formal Education (DAE)',
  'Library and Information Science (LIS)',
  ' Early Childhood and Primary Education (ECPE)',
  'Department of Economics',
  'Department of Geography & Environmental Management',
  'Department of Political & Administrative Studies',
  'Department of Sociology',
  'Centre for Conflicts & Gender Studies',
  'Centre for Logistics & Transport Studies',
  'Centre for Disaster Risk Management & Development Studies',
  'Internal Medicine',
  'Pediatrics and Child Health',
  'Anesthesiology',
  'Surgery',
  'Obstetrics & Gynecology',
  'Preventive & Social Medicine',
  'Nursing',
  'Radiology',
  'Mental Health',
  'Anatomy',
  'Physiology',
  'Pharmacology',
  'Anatomical Pathology',
  'Chemical Pathology',
  'Haematology, Blood Transfusion & Immunology',
  'Medical Microbiology',
  'Medical Biochemistry',
  'Restoration Dentistry',
  'Child Dental Health',
  'Oral & Maxillofacial Surgery',
  'Preventive& Social Dentistry',
  'Oral Pathology & Oral Biology',
  'Accounting',
  'Finance and Banking',
  'Management',
  'Marketing',
  'Hospitality Management and tourism',
  'Department of Anesthesiology',
  'Department of Internal Medicine',
  'Department of Mental Health',
  'Department of Nursing',
  'Department of Obstetrics and Gynecology',
  'Department of Pediatrics and Child Health',
  'Department of Preventive and Social Medicine',
  'Department of Radiology',
  'Department of Surgery',
  'Department of Agricultural Economics and Extension',
  'Department of Animal Science',
  'Department of Crop and Soil Science',
  'Department of Fisheries',
  'Department of Forestry and Wildlife',
  'Department of Animal & Environmental Biology',
  'Department of Microbiology',
  'Department of Plant Science & Biotechnology',
  'Department of Pure & Industrial Chemistry',
  'Department of Computer Science',
  'Department of Geology',
  'Department of Mathematics and Statistics',
  'Department of Physics',
  'Department of Biochemistry',
  'Department of Music',
  'Department of English Studies',
  'Department of Fine Arts and Design',
  'Department of Foreign Language & Literature',
  'Department of Religious and Cultural Studies',
  'Department of History & Diplomatic Studies',
  'Department of Philosophy',
  'Department of Theatre and Film Studies',
  'Department of Linguistics and Communication Studies',
  'Clinical Pharmacy and Management',
  'Pharmaceutical and Medicinal Chemistry',
  'Pharmaceutical Microbiology and Biotechnology',
  'Experimental Pharmacology and Toxicology',
];
