// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDv-XfymCvpHOgzg9SKixeUwEdJqVIqwM',
    appId: '1:299319567459:web:665b2c9a6a2918a609c456',
    messagingSenderId: '299319567459',
    projectId: 'automated-textbook-system',
    authDomain: 'automated-textbook-system.firebaseapp.com',
    storageBucket: 'automated-textbook-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmoMAEQU7T1PG5pIlUpCLeBOsWkSVLRew',
    appId: '1:299319567459:android:d7279285d9812f1009c456',
    messagingSenderId: '299319567459',
    projectId: 'automated-textbook-system',
    storageBucket: 'automated-textbook-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsC9lLS7nzJHz5WITeXxjf3Qvcuz-Cts4',
    appId: '1:299319567459:ios:604fa3ae3e82139109c456',
    messagingSenderId: '299319567459',
    projectId: 'automated-textbook-system',
    storageBucket: 'automated-textbook-system.appspot.com',
    iosBundleId: 'com.example.automatedTexbookSystem',
  );
}
